#!/usr/bin/env python3
"""Setup for flowlearn-mcp. Two modes:

  Interactive (default):
    python scripts/register.py
        Prompts for email and password. Signs in to flowlearn.io, lists your
        tenant memberships, and either auto-picks (if you admin one tenant) or
        asks you to pick from a numbered list.

  Non-interactive (Claude-callable):
    python scripts/register.py --email X --password Y [--slug Z] -y
        Same flow but never prompts. --slug is only required if you admin more
        than one tenant; with one tenant it's auto-detected. With multiple
        tenants and no --slug, the script lists the available slugs and exits.

In both modes the script writes .env, registers (or re-registers) the server
with Claude Code at user scope, and verifies the credentials end-to-end by
calling course.list. Use --no-verify to skip the verification call.

WARNING: passing --password as a CLI argument exposes it to shell history and
the process list. Prefer the interactive prompt for password entry.
"""
from __future__ import annotations

import argparse
import getpass
import json
import shutil
import subprocess
import sys
import urllib.error
import urllib.request
from http.cookiejar import CookieJar
from pathlib import Path

FLOWLEARN_BASE_URL = "https://flowlearn.io"
ADMIN_ROLES = ("tenant_admin", "creator", "super_admin")

PKG_ROOT = Path(__file__).resolve().parent.parent
ENV_PATH = PKG_ROOT / ".env"
SERVER_ENTRY = PKG_ROOT / "dist" / "index.js"
TESTS_DIR = PKG_ROOT / "tests"


def parse_env(path: Path) -> dict[str, str]:
    if not path.exists():
        return {}
    out: dict[str, str] = {}
    for raw in path.read_text(encoding="utf-8").splitlines():
        line = raw.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        k, _, v = line.partition("=")
        out[k.strip()] = v.strip().strip('"').strip("'")
    return out


def write_env(path: Path, values: dict[str, str]) -> None:
    lines = [
        "# Flowlearn MCP credentials. Generated by scripts/register.py.",
        "# Re-run scripts/register.py to change values.",
        "",
        f"FLOWLEARN_EMAIL={values['FLOWLEARN_EMAIL']}",
        f"FLOWLEARN_PASSWORD={values['FLOWLEARN_PASSWORD']}",
        f"FLOWLEARN_TENANT_SLUG={values['FLOWLEARN_TENANT_SLUG']}",
        "",
    ]
    path.write_text("\n".join(lines), encoding="utf-8")


def prompt_required(label: str, default: str = "") -> str:
    """Prompt with optional default. Re-asks until non-empty."""
    suffix = f" [{default}]" if default else ""
    while True:
        value = input(f"  {label}{suffix}: ").strip()
        if not value and default:
            return default
        if value:
            return value
        print("  (required)")


def prompt_password(existing: str) -> str:
    """Hidden password prompt. If a password is already set, allow keeping it."""
    if existing:
        keep = getpass.getpass(
            "  Password (press Enter to keep existing, or type to replace): "
        )
        return keep.strip() or existing
    while True:
        value = getpass.getpass("  Password: ").strip()
        if value:
            return value
        print("  (required)")


def fetch_memberships(email: str, password: str) -> list[dict]:
    """Sign in to flowlearn.io and return the user's tenant memberships.

    Returns a list of {tenant_id, slug, name, role}. Raises RuntimeError with a
    human-readable message on auth failure or network error.
    """
    cookie_jar = CookieJar()
    opener = urllib.request.build_opener(
        urllib.request.HTTPCookieProcessor(cookie_jar)
    )

    sign_in_req = urllib.request.Request(
        f"{FLOWLEARN_BASE_URL}/api/auth/sign-in/email",
        data=json.dumps({"email": email, "password": password}).encode("utf-8"),
        headers={
            "Content-Type": "application/json",
            "Origin": FLOWLEARN_BASE_URL,
        },
        method="POST",
    )
    try:
        opener.open(sign_in_req).read()
    except urllib.error.HTTPError as e:
        body = e.read().decode("utf-8", errors="replace")
        if e.code == 401:
            raise RuntimeError("sign-in failed: invalid email or password.")
        raise RuntimeError(f"sign-in failed (HTTP {e.code}): {body}")
    except urllib.error.URLError as e:
        raise RuntimeError(f"network error reaching flowlearn.io: {e.reason}")

    mem_req = urllib.request.Request(
        f"{FLOWLEARN_BASE_URL}/api/register/memberships",
        headers={"Origin": FLOWLEARN_BASE_URL},
    )
    try:
        with opener.open(mem_req) as resp:
            data = json.loads(resp.read().decode("utf-8"))
    except urllib.error.HTTPError as e:
        body = e.read().decode("utf-8", errors="replace")
        raise RuntimeError(f"memberships fetch failed (HTTP {e.code}): {body}")

    return data.get("memberships", [])


def pick_tenant(
    memberships: list[dict],
    requested_slug: str,
    non_interactive: bool,
) -> dict:
    """Choose one membership. Auto-picks if 1 admin tenant; prompts otherwise."""
    admin_memberships = [
        m for m in memberships if m.get("role") in ADMIN_ROLES
    ]

    if not admin_memberships:
        if memberships:
            roles = sorted({m["role"] for m in memberships})
            sys.exit(
                f"This account has memberships ({', '.join(roles)}) but none with "
                f"an admin role ({', '.join(ADMIN_ROLES)}). Ask a tenant admin to "
                f"upgrade your role, then re-run."
            )
        sys.exit(
            "This account has no tenant memberships. Sign in to flowlearn.io "
            "to confirm, then re-run."
        )

    if requested_slug:
        match = next(
            (m for m in admin_memberships if m["slug"] == requested_slug), None
        )
        if match:
            return match
        available = ", ".join(m["slug"] for m in admin_memberships)
        sys.exit(
            f"Requested slug '{requested_slug}' is not one of your admin "
            f"tenants. Available: {available}"
        )

    if len(admin_memberships) == 1:
        chosen = admin_memberships[0]
        print(
            f"  Auto-selected tenant: {chosen['slug']} "
            f"({chosen['name']!r}, role: {chosen['role']})"
        )
        return chosen

    if non_interactive:
        slugs = ", ".join(m["slug"] for m in admin_memberships)
        sys.exit(
            f"--non-interactive: multiple admin tenants available ({slugs}). "
            f"Pass --slug <one-of-them>."
        )

    print()
    print("  You have admin access to multiple tenants. Pick one:")
    for i, m in enumerate(admin_memberships, start=1):
        print(f"    [{i}] {m['slug']:<20} {m['name']}  (role: {m['role']})")
    while True:
        choice = input(f"  Number [1-{len(admin_memberships)}]: ").strip()
        try:
            idx = int(choice) - 1
            if 0 <= idx < len(admin_memberships):
                return admin_memberships[idx]
        except ValueError:
            pass
        print("  (invalid choice)")


def collect_creds(
    existing: dict[str, str],
    args: argparse.Namespace,
) -> dict[str, str]:
    """Email + password come from flags/.env/prompts; slug comes from a real
    membership lookup against flowlearn.io after sign-in."""
    email = args.email or existing.get("FLOWLEARN_EMAIL", "")
    password = args.password or existing.get("FLOWLEARN_PASSWORD", "")
    requested_slug = (args.slug or existing.get("FLOWLEARN_TENANT_SLUG", "")).lower()

    if args.non_interactive:
        missing = [
            label for label, value in [
                ("--email", email), ("--password", password),
            ] if not value
        ]
        if missing:
            sys.exit(
                f"--non-interactive: missing required value(s): {', '.join(missing)}. "
                f"Provide via flags or pre-populate .env."
            )
    else:
        print()
        print("Flowlearn credentials")
        print("---------------------")
        if email or password:
            print("(values in [brackets] are current; press Enter to keep)")
        email = prompt_required("Email", default=email)
        password = prompt_password(password)

    print()
    print("Looking up your tenant memberships on flowlearn.io...")
    try:
        memberships = fetch_memberships(email, password)
    except RuntimeError as e:
        sys.exit(f"  {e}")

    chosen = pick_tenant(memberships, requested_slug, args.non_interactive)

    return {
        "FLOWLEARN_EMAIL": email,
        "FLOWLEARN_PASSWORD": password,
        "FLOWLEARN_TENANT_SLUG": chosen["slug"],
    }


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(
        description="Register flowlearn-mcp with Claude Code.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    p.add_argument("--email", help="Tenant admin email")
    p.add_argument(
        "--password",
        help="Tenant admin password (WARNING: visible in shell history and process list)",
    )
    p.add_argument("--slug", help="Tenant slug (will be lowercased)")
    p.add_argument(
        "-y", "--non-interactive",
        action="store_true",
        help="Never prompt; fail if any required value is missing.",
    )
    p.add_argument(
        "--no-verify",
        action="store_true",
        help="Skip the post-registration course.list verification call.",
    )
    return p.parse_args()


def register_with_claude(values: dict[str, str]) -> None:
    if not shutil.which("claude"):
        sys.exit("`claude` CLI not found on PATH. Install Claude Code first.")

    # Best-effort remove from both scopes so re-registration is clean.
    for scope in ("user", "local"):
        subprocess.run(
            ["claude", "mcp", "remove", "flowlearn", "--scope", scope],
            check=False,
            capture_output=True,
        )

    cmd = [
        "claude", "mcp", "add", "flowlearn",
        "--scope", "user",
        "--transport", "stdio",
        "--env", f"FLOWLEARN_EMAIL={values['FLOWLEARN_EMAIL']}",
        "--env", f"FLOWLEARN_PASSWORD={values['FLOWLEARN_PASSWORD']}",
        "--env", f"FLOWLEARN_TENANT_SLUG={values['FLOWLEARN_TENANT_SLUG']}",
        "--", "node", str(SERVER_ENTRY),
    ]
    result = subprocess.run(cmd)
    if result.returncode != 0:
        sys.exit(
            f"`claude mcp add` failed (exit {result.returncode}). "
            "Fix the issue and re-run."
        )


def verify_credentials(values: dict[str, str]) -> bool:
    """Spawn the MCP server and make one real call to confirm auth works."""
    mcp_client_path = TESTS_DIR / "mcp_client.py"
    if not mcp_client_path.exists():
        print(
            "\n(skipping verification — tests/mcp_client.py not found. "
            "Try the MCP from a Claude Code session to confirm it works.)"
        )
        return True

    sys.path.insert(0, str(TESTS_DIR))
    try:
        from mcp_client import McpClient, McpToolError, McpServerError  # type: ignore
    except ImportError as e:
        print(f"\n(skipping verification — could not import mcp_client: {e})")
        return True

    print("\nVerifying credentials (calling course.list)...")
    try:
        client = McpClient(SERVER_ENTRY, values)
    except Exception as e:
        print(f"  FAILED to start MCP server: {e}")
        return False

    try:
        result = client.call_tool("course.list", {})
    except McpToolError as e:
        print(f"  FAILED: {e.message.strip()}")
        return False
    except McpServerError as e:
        print(f"  FAILED (server error): {e}")
        return False
    finally:
        client.close()

    if isinstance(result, list):
        count = len(result)
    elif isinstance(result, dict) and "courses" in result:
        count = len(result["courses"])
    else:
        count = "?"
    print(f"  OK — sign-in succeeded, tenant resolved, {count} course(s) visible.")
    return True


def main() -> int:
    args = parse_args()

    if not SERVER_ENTRY.exists():
        sys.exit(
            f"Build artifact missing: {SERVER_ENTRY}\n"
            f"Run `npm install && npm run build` in {PKG_ROOT} first."
        )

    existing = parse_env(ENV_PATH)
    values = collect_creds(existing, args)

    write_env(ENV_PATH, values)
    print(f"Wrote {ENV_PATH.name}")

    register_with_claude(values)
    print(f"Registered flowlearn MCP (user scope) for tenant '{values['FLOWLEARN_TENANT_SLUG']}'.")

    if args.no_verify:
        print("Skipped credential verification (--no-verify).")
    else:
        ok = verify_credentials(values)
        if not ok:
            print()
            print("Registration completed but credentials FAILED verification.")
            print("Re-run scripts/register.py to fix the values, or check the error above.")
            return 1

    print()
    print("All set. If a Claude Code session is already open, restart it to pick up the new server.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
